### ISSUE TITLE
Module compilation fails

### ISSUE THREAD

**Issue by tbourgain** [hubertqc/selinux_springboot#11]
Hello,

Compilation is failling, "filetrans_add_pattern" transitions shoudl be put outside of the "if      (allow_springboot_dynamic_libs)" :

/usr/bin/make -f /usr/share/selinux/devel/Makefile springboot.pp
Compiling targeted springboot module
springboot.te:240:ERROR 'type transitions with a filename not allowed inside conditionals
' at token ';' on line 5791:
#line 240
        type_transition springboot_t springboot_var_t:dir springboot_dynlib_t "lib" ;
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [/usr/share/selinux/devel/include/Makefile:157: tmp/springboot.mod] Error 1

Thank you !

**Comment by hubertqc** [comment]
Bug was introduced with #10
